services:
  app:
    build: .
    depends_on:
      - songs_db
    command: "bash ./scripts/runlocal.sh"
    volumes:
      - .:/usr/src/app
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - MONGO_URI=mongodb://songs_db:27017
      - VERBOSE_FLASK=true
      - FLASK_ENV=development
      - DB_NAME=songs
    networks:
      - custom

  songs_db:
    image: mongo:5.0
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - custom

networks:
  custom:
    driver: bridge
